### ISSUE TITLE
Complete code for Dilation in 50*50 maze

### ISSUE THREAD

**Issue by supu2701** [supu2701/Open-CV-Projects#1]
In Open-CV-Projects/Solve the Maze/50x50/MazeSolver50*50.py file, write the complete code for dilation. Reference can be taken from the screenshot given below 
![issue1](https://user-images.githubusercontent.com/58454886/101048955-11d74d80-35a9-11eb-825b-852d3710801f.PNG)

**Comment by Gaurav7888** [comment]
I want to work upon this issue.

**Comment by Gaurav7888** [comment]
@supu2701 I have working knowledge of dilation and erosion using opencv . Can I start working upon this issue.

**Comment by supu2701** [comment]
> @supu2701 I have working knowledge of dilation and erosion using opencv . Can I start working upon this issue.

You have already been assigned the issue #3 . Do you want to work on this issue also simultaneously?

**Comment by Gaurav7888** [comment]
At that time u didnt assign me any work so i commented .

**Comment by NiharikaVadlamudi** [comment]
This can be fixed by me , pls assign it .

**Comment by asthabhatiwara** [comment]
I want to work upon this .I have done a project in the filed of opencv.

**Comment by asthabhatiwara** [comment]
Hii ,I want to work upon this issue .I have done a project in the field of OpenCV.

**Comment by supu2701** [comment]
> This can be fixed by me , pls assign it .

@NiharikaVadlamudi  You have been assigned this issue. You can start working on it. Good luck

**Comment by Tanvie** [comment]
@supu2701 I would like to work on this issue. I have prior knowledge of working with OpenCV.

**Comment by LakhanMardi** [comment]
Can I work on this. I have done few projects on OpenCV

**Comment by NiharikaVadlamudi** [comment]
@supu2701 I think half of the maze is not identified by find_contours ()  [ I am done with dilation part , but I am asking is this your desired output. The entire contour must be found right ? ] 
![Screenshot from 2020-12-07 13-02-28](https://user-images.githubusercontent.com/58340986/101322294-c95fae80-388c-11eb-9a71-50af51664397.png)
