### ISSUE TITLE
Harris Corner Detection

### ISSUE THREAD

**Issue by supu2701** [supu2701/Open-CV-Projects#17]
Complete the code snippet in the file Open-CV-Projects/Detection machine/Find Corner/harriscorners.py to detect the Harris Corner. Refer to the readme.md file present in the Find Corner folder which contains the detailed information about the good corner feature

**Comment by NiharikaVadlamudi** [comment]
I can work on this ! Pls assign it to me

**Comment by supu2701** [comment]
NiharikaVadlamudi has been assigned another issue, anybody else who want to take up the issue can comment here.

**Comment by NiharikaVadlamudi** [comment]
@supu2701 I've completed the previous task (check my latest PR) , so you can assign this to me .

**Comment by supu2701** [comment]
> @supu2701 I've completed the previous task (check my latest PR) , so you can assign this to me .

@NiharikaVadlamudi Have you made the PR of the issue which was assigned to you earlier. Once you complete the previous one, then only you can make the PR for this one. Kindly make the previous on first. 
I aslo observed that you made PR for this one so for now I am assigning you this issue also, but do keep in mind for next time to comment and then after you are  being assigned then only make the PR.

**Comment by NiharikaVadlamudi** [comment]
@supu2701  Sorry for the confusion ! I've completed this task ( before you've assigned it to me ) (My PR says HarrisCorner Detection ) . Yep! Sure , next time I'll ensure that you assign the task to me first ! Pls checkout my PR

**Comment by supu2701** [comment]
> @supu2701 Sorry for the confusion ! I've completed this task ( before you've assigned it to me ) (My PR says HarrisCorner Detection ) . Yep! Sure , next time I'll ensure that you assign the task to me first ! Pls checkout my PR

@NiharikaVadlamudi Yes sure. Will review your PR shortly.
