### ISSUE TITLE
Face detection using camera

### ISSUE THREAD

**Issue by supu2701** [supu2701/Open-CV-Projects#19]
Edit the Open-CV-Projects/Detection machine/Face&Eye Detection/face_detection_camera.py file  such that it detects the face of a person from the webcam. To chane from inbuilt webcam to external webcam, only you have to change the following:  "cap = cv2.VideoCapture(0)" to cap = cv2.VideoCapture(1).

**Comment by vineethpilli** [comment]
I want to work upon this issue.Can you please assign it to me?

**Comment by supu2701** [comment]
@vineethpilli You have been assigned this issue. You can sart working on it👍

**Comment by vineethpilli** [comment]
@supu2701  I have resolved this issue.Please look into my PR and let me know if any changes needed.
