### ISSUE TITLE
Face and eye detection using camera

### ISSUE THREAD

**Issue by supu2701** [supu2701/Open-CV-Projects#21]
Edit the Open-CV-Projects/Detection machine/Face&Eye Detection/face_eye_detection_camera.py file as per mentioned in Readme.md

**Comment by psaimahesh** [comment]
I want to work upon this issue. Could you assign it to me?

**Comment by supu2701** [comment]
@psaimahesh You have been assigned this issue. You can sart working on it👍

**Comment by psaimahesh** [comment]
I have completed the task. Please check out my PR
