### ISSUE TITLE
Toonify Image

### ISSUE THREAD

**Issue by Tejas1510** [supu2701/Open-CV-Projects#24]
A python application that takes an image as input and toonify it (make a cartoonist image) using Open CV and I will use the following API https://deepai.org/machine-learning-model/toonify API.

**Comment by Tejas1510** [comment]
@supu2701 Can I work on it

**Comment by supu2701** [comment]
> A python application that takes an image as input and toonify it (make a cartoonist image) using Open CV and I will use the following API https://deepai.org/machine-learning-model/toonify API.

OK You can work on it, just create a folder inside "Project 3" directory for your application and include the details of you application( like a small description, resources and a working screenshots) in the Readme.md file present at "Project 3" Directory.
