### ISSUE TITLE
Complete code for Splitting channel of maze in 20*20 maze

### ISSUE THREAD

**Issue by supu2701** [supu2701/Open-CV-Projects#3]
In Open-CV-Projects/Solve the Maze/20x20/MazeSolver 20*20.py file, write the complete code for dilation. Reference can be taken from the screenshot given below

![issue3](https://user-images.githubusercontent.com/58454886/101053395-be1b3300-35ad-11eb-8017-003db33e41ff.PNG)

**Comment by Gaurav7888** [comment]
I want to work upon this issue.

**Comment by amoghatsunil** [comment]
can i work on this issue?  @supu2701

**Comment by supu2701** [comment]
> I want to work upon this issue.@supu2701

You have been assigned this issue. You can start working on it.

**Comment by Gaurav7888** [comment]
@supu2701  thx, I have started working on this issue.

**Comment by supu2701** [comment]
@Gaurav7888 Please do complete fixing of this issue latest by tomorrow, otherwise it will be assigned to the next contributor. In case you are facing any doubts regarding this, you can ask on the slack channel.

**Comment by Gaurav7888** [comment]
@supu2701  ok i will complete it by tonight  , thx for pre warning!
