### ISSUE TITLE
Complete the logic for 5*5 maze.py

### ISSUE THREAD

**Issue by supu2701** [supu2701/Open-CV-Projects#4]
Complete the logic for the 5*5 maze in Open-CV-Projects/Solve the Maze/5x5/MazeSolver 5*5.py file. Reference can be taken from the code template already present in the file.

**Comment by Gaurav7888** [comment]
@supu2701  I want to work upon this issue

**Comment by srinath1412001** [comment]
I have worked on this earlier.. If you assign it to me i'll make a pull request.
![5x5](https://user-images.githubusercontent.com/47494475/101232673-ece1f800-36d8-11eb-868c-845b7ee34f3c.jpg)
![test](https://user-images.githubusercontent.com/47494475/101232674-ef445200-36d8-11eb-8adc-889dfb8e7534.png)

**Comment by supu2701** [comment]
> I have worked on this earlier.. If you assign it to me i'll make a pull request.
> ![5x5](https://user-images.githubusercontent.com/47494475/101232673-ece1f800-36d8-11eb-868c-845b7ee34f3c.jpg)
> ![result](https://user-images.githubusercontent.com/47494475/101234362-a1cde200-36e4-11eb-8ab8-878835d4c42c.jpg)

@srinath1412001 You have been assigned this issue. You can start working on it.

**Comment by srinath1412001** [comment]
@supu2701 Is is fine if submit it in the form of an ipython notebook?
