### ISSUE TITLE
Suggestion to make a separate CONTRIBUTING.md file.

### ISSUE THREAD

**Issue by srinath1412001** [supu2701/Open-CV-Projects#8]
It would be good to move the 'How to contribute?' section in a separate CONTRIBUTING.md file.
Later you could add a link to that file in the Readme section. This way the readme can be used to describe only the projects.

**Comment by supu2701** [comment]
Anyone who want to do the necessary changes can comment to get him/herself assigned

**Comment by Tejas1510** [comment]
@supu2701 Can I go for it

**Comment by supu2701** [comment]
Tejas1510 has been assigned another issue anyone who want to make the required changes can comment.

**Comment by supu2701** [comment]
> It would be good to move the 'How to contribute?' section in a separate CONTRIBUTING.md file.
> Later you could add a link to that file in the Readme section. This way the readme can be used to describe only the projects.

@srinath1412001 Do you want to contribute to this issue? You can comment to get yourself assigned with it.

**Comment by srinath1412001** [comment]
@supu2701 Sure, I'll get it done.
