### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by Tejas1510** [supu2701/Open-CV-Projects#9]
The project is currently missing the Code of Conduct file which is important for open source project
So can I go for it @supu2701

**Comment by supu2701** [comment]
> The project is currently missing the Code of Conduct file which is important for open source project
> So can I go for it @supu2701

@Tejas1510 You have been assigned this issue. You can start working on it👍

**Comment by Tejas1510** [comment]
Sure @supu2701 will make a pr soon

**Comment by Tejas1510** [comment]
@supu2701 Can you please update the leaderboard with the point associated with merged PR
